version: "3.1"

services:
  app:
    build: .
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: monitor
      POSTGRES_DB: monitor
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d
